[project]
name = "core"
version = "0.1.0"
authors = [{ name = "Hinsun", email = "vanhoai.adv@gmail.com" }]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
core = "core:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
